apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jhdx4m286-nodejs 
  janus-idp.io/tekton: jhdx4m286-nodejs
  backstage.io/kubernetes-id: jhdx4m286-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jhdx4m286-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  