apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: jhdx4m286-nodejs-gitops
  description: This is GitOps manifest for jhdx4m286-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: jhdx4m286-nodejs
    backstage.io/kubernetes-id: jhdx4m286-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: jhdx4m286-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:jhdx4m286-nodejs
