apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jhdx4m286-nodejs
  janus-idp.io/tekton: jhdx4m286-nodejs
  backstage.io/kubernetes-id: jhdx4m286-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jhdx4m286-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
